[package]
name = "gh-start"
version = "0.1.0"
authors = ["Jason Antwi-Appah <hey@jasonaa.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
inquire = "0.0.8"
